import { Share1Icon } from '@radix-ui/react-icons';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { Button } from '../components/Button/Button';
import { Input } from '../components/Input/Input';
import { Text } from '../components/Text/text';
import { Timer } from '../components/Timer/timer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ekiwok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/noto_melting-facefavicon-emoji.png" />
      </Head>
      <Input sizeOfInput="md" placeholder="USER12345" iconPosition="left" />
      <Input sizeOfInput="sm" iconPosition="right" />
      <div>
        <Button text="ZASADY GRY" transparent />
        <Button text="ZACZNIJ GRĘ" />
      </div>
      <div className="flex">
        <Button text="Link do gry" icon={<Share1Icon className="fill-content w-7 h-7 mr-2" />} size="sm" />
        <Button text="Zasady" transparent size="sm" />
      </div>
      <Text>to jest przyklad</Text>
      <Timer seconds={15} onEnd={() => console.log('Koniec gry')} />
      <Link href="/Game/">
        <a>Game</a>
      </Link>
      <Link href="/Game1/">
        <a>Game1</a>
      </Link>
    </div>
  );
};

export default Home;
