import { Emoji } from 'components/Emoji/emoji';
import { CreateGame } from 'modules/auth/components/CreateGame';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { Avatar } from '../components/Avatar/Avatar';
import { Badge } from '../components/Badge/Badge';
import { Button } from '../components/Button/Button';
import { Icon } from '../components/Icon/Icon';
import { Input } from '../components/Input/Input';
import { Logo } from '../components/Logo/logo';
import { Text } from '../components/Text/text';
import { Timer } from '../components/Timer/timer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ekiwok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/noto_melting-facefavicon-emoji.png" />
      </Head>
      <Input sizeOfInput="md" placeholder="USER12345" icon={<Icon type="user" size="md" />} iconPosition="left" />
      <Input sizeOfInput="sm" iconPosition="right" icon={<Icon type="emotikon" size="sm" />} />
      <Logo width="366px" height="103px" />
      <div>
        <Button text="ZASADY GRY" transparent />
        <Button text="ZACZNIJ GRĘ" />
      </div>
      <div className="flex">
        <Button text="Link do gry" icon={<Icon type="share" className="mr-3" />} />
        <Button text="Zasady" transparent size="sm" />
      </div>
      <div className="flex items-center">
        <Badge variant="filled" count={13} size="lg" />
        <Badge count={8} size="sm" />
      </div>
      <Text>to jest przyklad</Text>
      <CreateGame />
      <Timer seconds={15} onEnd={() => console.log('Koniec gry')} />
      <Link href="/Game/">
        <a>Game</a>
      </Link>

      <div className="flex items-center">
        <Avatar username="Arnold" avatarNo={6} />
        <Avatar username="Wąsek" avatarNo={3} size="lg" />
        <Avatar username="Munio" avatarNo={4} size="sm" />
      </div>
      <Emoji icon="noto:anguished-face" size="lg" />
      <Emoji icon="noto:pensive-face" size="sm" />
      <Emoji icon="noto:smiling-face-with-smiling-eyes" size="md" />
    </div>
  );
};

export default Home;
