import { Share1Icon } from '@radix-ui/react-icons'
import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '../components/Logo/Button/Button';
import { Logo } from '../components/Logo/logo'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ekiwok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/noto_melting-facefavicon-emoji.png" />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@800" rel="stylesheet" />
      </Head>
      <Logo />
      <div>
        <Button text="ZASADY GRY" transparent />
        <Button text="ZACZNIJ GRĘ" />
      </div>
      <div className="flex">
        <Button text="Link do gry" icon={<Share1Icon className='fill-content w-7 h-7 mr-2' />} buttonSize="sm" />
        <Button text="Zasady" transparent buttonSize="sm" />
      </div>
    </div>
  );
};

export default Home;
